name:                lab09
version:             0.1.0.0
github:              "shreddered/lab09"
license:             BSD3
author:              "Dmitry Kalinin"
maintainer:          "x.shreddered.x@gmail.com"
copyright:           "2022 Dmitry Kalinin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/shreddered/lab09#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- containers
- optparse-applicative

library:
  source-dirs: src

executables:
  lab09-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lab09

tests:
  lab09-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lab09
